### ISSUE TITLE
Could not retrieve file size of the cover art

### ISSUE THREAD

**Issue by kokoropop** [Otiel/BandcampDownloader#185] opened 2021-07-16 08:56 UTC
Application doesn't work from yesterday.
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/6829295/BandcampDownloader.log)

**Comment by Otiel** [comment] 2021-07-19 14:58
I can't reproduce, does that happen for every album?

Have you been maybe downloading lots of album recently? If so, Bandcamp anti-spam mechanism may have been triggered for you.

**Comment by kokoropop** [comment] 2021-07-20 07:17
After few days in troubles with this I found that problem ties with downloading covers. I disabled "Save" in cover art section and it works.

**Comment by hstntt** [comment] 2021-07-26 19:06
I have the same problem with downloading cover art. Tested on different albums.

```
21:47:03 Starting download...
21:47:03 Retrieving album data for https://hotelpoolsmusic.bandcamp.com/album/palmscapes
21:47:05 Computing size for album "Palmscapes"...
21:47:05 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 1 of 7
21:47:06 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 2 of 7
21:47:09 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 3 of 7
21:47:22 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 4 of 7
21:48:14 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 5 of 7

21:48:59 Starting download...
21:48:59 Retrieving album data for https://hotelpoolsmusic.bandcamp.com/track/u-f-o
21:49:02 Computing size for album "U.F.O"...
21:49:02 Failed to retrieve the size of the cover art file for album "U.F.O". Try 1 of 7
21:49:03 Failed to retrieve the size of the cover art file for album "U.F.O". Try 2 of 7
21:49:06 Failed to retrieve the size of the cover art file for album "U.F.O". Try 3 of 7
21:49:19 Failed to retrieve the size of the cover art file for album "U.F.O". Try 4 of 7

21:50:29 Starting download...
21:50:29 Retrieving album data for https://popgroup.bandcamp.com/album/alien-blood
21:50:31 Computing size for album "Alien Blood"...
21:50:32 Failed to retrieve the size of the cover art file for album "Alien Blood". Try 1 of 7
21:50:32 Failed to retrieve the size of the cover art file for album "Alien Blood". Try 2 of 7
21:50:36 Failed to retrieve the size of the cover art file for album "Alien Blood". Try 3 of 7
21:50:49 Failed to retrieve the size of the cover art file for album "Alien Blood". Try 4 of 7
```

**Comment by Otiel** [comment] 2021-07-26 20:58
There's a bug I haven't had the time to look around yet, for some people downloading the cover art fails. Try disabling both options for the download of the cover art.

**Comment by Otiel** [comment] 2021-07-27 11:24
@hstntt Can you access this URL from your browser?

https://f4.bcbits.com/img/a4150604722_0.jpg

**Comment by hstntt** [comment] 2021-07-27 11:29
Yes, image is available.

**Comment by Otiel** [comment] 2021-07-27 11:38
Wait -- I read the logs wrong, sorry. It is only the file size of the cover art that cannot be retrieved, but the cover art is correctly downloaded if you let it continue. Do you confirm?

**Comment by hstntt** [comment] 2021-07-27 12:32
It takes quite a long time before the application goes through all 7 tries twice. The default delay between the last two attempts is too long (only now I saw that it could be changed). 
As a result, the audio files are downloaded, but the cover art is not. 

<details>
 <summary>Log</summary>

```js
14:30:12 Starting download...
14:30:12 Retrieving album data for https://hotelpoolsmusic.bandcamp.com/album/palmscapes
14:30:14 Computing size for album "Palmscapes"...
14:30:14 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 1 of 7
14:30:15 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 2 of 7
14:30:19 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 3 of 7
14:30:32 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 4 of 7
14:31:23 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 5 of 7
14:34:48 Failed to retrieve the size of the cover art file for album "Palmscapes". Try 6 of 7
14:48:27 Failed to retrieve the size of the cover art file for album "Palmscapes". Hit max retries of 7. Progress update may be wrong.
14:48:28 Retrieved the size of the MP3 file for the track "Crush"
14:48:28 Retrieved the size of the MP3 file for the track "Splash feat. VIQ"
14:48:28 Retrieved the size of the MP3 file for the track "Polaris feat. Echosoft"
14:48:28 Retrieved the size of the MP3 file for the track "Cherry feat. Upusen"
14:48:28 Retrieved the size of the MP3 file for the track "Hunny"
14:48:28 Retrieved the size of the MP3 file for the track "Nowtro"
14:48:28 Retrieved the size of the MP3 file for the track "Coco feat. Forhill"
14:48:28 Retrieved the size of the MP3 file for the track "Oceanside"
14:48:28 Retrieved the size of the MP3 file for the track "Vacation"
14:48:28 Retrieved the size of the MP3 file for the track "Bonfire feat. Decisive Koala"
14:48:28 Retrieved the size of the MP3 file for the track "Genesis"
14:48:28 Retrieved the size of the MP3 file for the track "Hideaway feat. Krosia"
14:48:28 Retrieved the size of the MP3 file for the track "Waves"
14:48:28 Unable to download artwork for album "Palmscapes". Try 1 of 7
14:48:29 Unable to download artwork for album "Palmscapes". Try 2 of 7
14:48:32 Unable to download artwork for album "Palmscapes". Try 3 of 7
14:48:45 Unable to download artwork for album "Palmscapes". Try 4 of 7
14:49:37 Unable to download artwork for album "Palmscapes". Try 5 of 7
14:53:02 Unable to download artwork for album "Palmscapes". Try 6 of 7
15:06:41 Unable to download artwork for album "Palmscapes". Try 7 of 7
15:06:41 Downloading track "Vacation" from url: https://t4.bcbits.com/stream/7440efe7d8b0a22ed80b4c4904a24d70/mp3-128/511589452?p=0&ts=1627472701&t=b8afa27d4d85194fa5a8a371c867c9a6f25a960c&token=1627472701_29f412bcde67af09896509db4df65632d59f97f5
15:06:41 Downloading track "Oceanside" from url: https://t4.bcbits.com/stream/a2b3949fb4ca752c8ffdbc384a0bebe9/mp3-128/146860456?p=0&ts=1627472701&t=3ca7b489aff50182e3cf9bfa614e992318db2e66&token=1627472701_a0bec548bff6e2488e1954baf832d8759a2866a1
15:06:41 Downloading track "Hideaway feat. Krosia" from url: https://t4.bcbits.com/stream/0c706eb3a1d34741ec300e894acf8216/mp3-128/761210914?p=0&ts=1627472701&t=b7a932821b9a0dbb37aaf9b5afc4b119114913e4&token=1627472701_e898627882102ff7b8ec5dfd2c69dcdf45aa3958
15:06:41 Downloading track "Waves" from url: https://t4.bcbits.com/stream/7fcb77d0b91e87e40981299812a27078/mp3-128/3673929946?p=0&ts=1627472701&t=456b5cefe6993f398243305295969a398c71e01c&token=1627472701_aa68cc1e6323c1c759613e53dad7464a6b0d2840
15:06:41 Downloading track "Splash feat. VIQ" from url: https://t4.bcbits.com/stream/7fbbf0aaae00088ceaae0e1acbb78037/mp3-128/85892287?p=0&ts=1627472701&t=dffa4a630a2a9b4fbf807fa00e6dcafc9ce1a348&token=1627472701_b24a9df3556b20bcd805fce151204c22de119074
15:06:41 Downloading track "Bonfire feat. Decisive Koala" from url: https://t4.bcbits.com/stream/7594ad377514bd313ac90bf7c4901fdb/mp3-128/2095068185?p=0&ts=1627472701&t=cfeceffee211b36c48de031208d8951e0bf415c4&token=1627472701_0fbfb017c1d76a0d777e09a3be45056406e915e1
15:06:41 Downloading track "Nowtro" from url: https://t4.bcbits.com/stream/4c0a75f7890f761a9f86412b34a3d9e9/mp3-128/780474428?p=0&ts=1627472701&t=dbd4d4d173263fb7bf1c5857c1916373d682ad8c&token=1627472701_5f2099658b6976dc5167d97fd923457197a60ae7
15:06:41 Downloading track "Hunny" from url: https://t4.bcbits.com/stream/6685c4997d402ed4124369793438f8af/mp3-128/366458343?p=0&ts=1627472701&t=584abeb0e5703064167c623309fe02e0b9d3f603&token=1627472701_c74a2a65a26a287615b29e0cee1152c9e57cba9b
15:06:41 Downloading track "Coco feat. Forhill" from url: https://t4.bcbits.com/stream/319b9bfaa6b09fadcb92a3a9194fce7f/mp3-128/1131998842?p=0&ts=1627472701&t=3f537d258804a35672a16d3050013eee3e30c3e3&token=1627472701_7b70bce984ea96deab1f5877bc9d307a6fc5f973
15:06:41 Downloading track "Cherry feat. Upusen" from url: https://t4.bcbits.com/stream/1fa3762a7e99ed43a5700d9fc25e66f2/mp3-128/2229964102?p=0&ts=1627472701&t=2b07d1ecad9a1ad7970e3509072fa84c923c5711&token=1627472701_6158aebb8d8ee80735acc008e925e8fbab19b258
15:06:41 Downloading track "Genesis" from url: https://t4.bcbits.com/stream/8feb298819ca4ef40866e8d89626c0db/mp3-128/4178546517?p=0&ts=1627472701&t=4741685a44c0da45e6def3a9ed11fb195d9686bc&token=1627472701_65d2ece404fbe0870487a8cf62b0d40fd9f500f0
15:06:41 Downloading track "Polaris feat. Echosoft" from url: https://t4.bcbits.com/stream/4e2791b1fa0b53007c762aac1939681e/mp3-128/1237573797?p=0&ts=1627472701&t=945f27692ccb8e3877c80c56af1d25bf4843717a&token=1627472701_d4964763f7ce57922466df47cde3ac4fba82d96c
15:06:42 Downloading track "Crush" from url: https://t4.bcbits.com/stream/f3835ed87fbf5ceb80dfb1ac3c4f3089/mp3-128/3422877558?p=0&ts=1627472701&t=08d3c37002bbe6f22ad0069742b1a482fdd11e21&token=1627472701_2443104424aa28c6f2c530d2fea993bf93b91fb5
15:06:45 Downloaded track "Nowtro" from url: https://t4.bcbits.com/stream/4c0a75f7890f761a9f86412b34a3d9e9/mp3-128/780474428?p=0&ts=1627472701&t=dbd4d4d173263fb7bf1c5857c1916373d682ad8c&token=1627472701_5f2099658b6976dc5167d97fd923457197a60ae7
15:06:45 Tags saved for track "07. Hotel Pools - Nowtro.mp3" from album "Palmscapes"
15:06:45 Downloaded track "07. Hotel Pools - Nowtro.mp3" from album "Palmscapes"
15:06:47 Downloaded track "Bonfire feat. Decisive Koala" from url: https://t4.bcbits.com/stream/7594ad377514bd313ac90bf7c4901fdb/mp3-128/2095068185?p=0&ts=1627472701&t=cfeceffee211b36c48de031208d8951e0bf415c4&token=1627472701_0fbfb017c1d76a0d777e09a3be45056406e915e1
15:06:47 Tags saved for track "06. Hotel Pools - Bonfire feat. Decisive Koala.mp3" from album "Palmscapes"
15:06:47 Downloaded track "06. Hotel Pools - Bonfire feat. Decisive Koala.mp3" from album "Palmscapes"
15:06:47 Downloaded track "Hideaway feat. Krosia" from url: https://t4.bcbits.com/stream/0c706eb3a1d34741ec300e894acf8216/mp3-128/761210914?p=0&ts=1627472701&t=b7a932821b9a0dbb37aaf9b5afc4b119114913e4&token=1627472701_e898627882102ff7b8ec5dfd2c69dcdf45aa3958
15:06:47 Tags saved for track "03. Hotel Pools - Hideaway feat. Krosia.mp3" from album "Palmscapes"
15:06:47 Downloaded track "03. Hotel Pools - Hideaway feat. Krosia.mp3" from album "Palmscapes"
15:06:47 Downloaded track "Vacation" from url: https://t4.bcbits.com/stream/7440efe7d8b0a22ed80b4c4904a24d70/mp3-128/511589452?p=0&ts=1627472701&t=b8afa27d4d85194fa5a8a371c867c9a6f25a960c&token=1627472701_29f412bcde67af09896509db4df65632d59f97f5
15:06:48 Tags saved for track "01. Hotel Pools - Vacation.mp3" from album "Palmscapes"
15:06:48 Downloaded track "01. Hotel Pools - Vacation.mp3" from album "Palmscapes"
15:06:49 Downloaded track "Crush" from url: https://t4.bcbits.com/stream/f3835ed87fbf5ceb80dfb1ac3c4f3089/mp3-128/3422877558?p=0&ts=1627472701&t=08d3c37002bbe6f22ad0069742b1a482fdd11e21&token=1627472701_2443104424aa28c6f2c530d2fea993bf93b91fb5
15:06:49 Tags saved for track "13. Hotel Pools - Crush.mp3" from album "Palmscapes"
15:06:49 Downloaded track "13. Hotel Pools - Crush.mp3" from album "Palmscapes"
15:06:49 Downloaded track "Polaris feat. Echosoft" from url: https://t4.bcbits.com/stream/4e2791b1fa0b53007c762aac1939681e/mp3-128/1237573797?p=0&ts=1627472701&t=945f27692ccb8e3877c80c56af1d25bf4843717a&token=1627472701_d4964763f7ce57922466df47cde3ac4fba82d96c
15:06:49 Tags saved for track "12. Hotel Pools - Polaris feat. Echosoft.mp3" from album "Palmscapes"
15:06:49 Downloaded track "12. Hotel Pools - Polaris feat. Echosoft.mp3" from album "Palmscapes"
15:06:50 Downloaded track "Oceanside" from url: https://t4.bcbits.com/stream/a2b3949fb4ca752c8ffdbc384a0bebe9/mp3-128/146860456?p=0&ts=1627472701&t=3ca7b489aff50182e3cf9bfa614e992318db2e66&token=1627472701_a0bec548bff6e2488e1954baf832d8759a2866a1
15:06:50 Tags saved for track "02. Hotel Pools - Oceanside.mp3" from album "Palmscapes"
15:06:50 Downloaded track "02. Hotel Pools - Oceanside.mp3" from album "Palmscapes"
15:06:50 Downloaded track "Cherry feat. Upusen" from url: https://t4.bcbits.com/stream/1fa3762a7e99ed43a5700d9fc25e66f2/mp3-128/2229964102?p=0&ts=1627472701&t=2b07d1ecad9a1ad7970e3509072fa84c923c5711&token=1627472701_6158aebb8d8ee80735acc008e925e8fbab19b258
15:06:50 Tags saved for track "10. Hotel Pools - Cherry feat. Upusen.mp3" from album "Palmscapes"
15:06:50 Downloaded track "10. Hotel Pools - Cherry feat. Upusen.mp3" from album "Palmscapes"
15:06:50 Downloaded track "Genesis" from url: https://t4.bcbits.com/stream/8feb298819ca4ef40866e8d89626c0db/mp3-128/4178546517?p=0&ts=1627472701&t=4741685a44c0da45e6def3a9ed11fb195d9686bc&token=1627472701_65d2ece404fbe0870487a8cf62b0d40fd9f500f0
15:06:50 Tags saved for track "11. Hotel Pools - Genesis.mp3" from album "Palmscapes"
15:06:50 Downloaded track "11. Hotel Pools - Genesis.mp3" from album "Palmscapes"
15:06:51 Downloaded track "Coco feat. Forhill" from url: https://t4.bcbits.com/stream/319b9bfaa6b09fadcb92a3a9194fce7f/mp3-128/1131998842?p=0&ts=1627472701&t=3f537d258804a35672a16d3050013eee3e30c3e3&token=1627472701_7b70bce984ea96deab1f5877bc9d307a6fc5f973
15:06:51 Tags saved for track "09. Hotel Pools - Coco feat. Forhill.mp3" from album "Palmscapes"
15:06:51 Downloaded track "09. Hotel Pools - Coco feat. Forhill.mp3" from album "Palmscapes"
15:06:51 Downloaded track "Waves" from url: https://t4.bcbits.com/stream/7fcb77d0b91e87e40981299812a27078/mp3-128/3673929946?p=0&ts=1627472701&t=456b5cefe6993f398243305295969a398c71e01c&token=1627472701_aa68cc1e6323c1c759613e53dad7464a6b0d2840
15:06:51 Tags saved for track "04. Hotel Pools - Waves.mp3" from album "Palmscapes"
15:06:51 Downloaded track "04. Hotel Pools - Waves.mp3" from album "Palmscapes"
15:06:52 Downloaded track "Hunny" from url: https://t4.bcbits.com/stream/6685c4997d402ed4124369793438f8af/mp3-128/366458343?p=0&ts=1627472701&t=584abeb0e5703064167c623309fe02e0b9d3f603&token=1627472701_c74a2a65a26a287615b29e0cee1152c9e57cba9b
15:06:52 Tags saved for track "08. Hotel Pools - Hunny.mp3" from album "Palmscapes"
15:06:52 Downloaded track "08. Hotel Pools - Hunny.mp3" from album "Palmscapes"
15:06:52 Downloaded track "Splash feat. VIQ" from url: https://t4.bcbits.com/stream/7fbbf0aaae00088ceaae0e1acbb78037/mp3-128/85892287?p=0&ts=1627472701&t=dffa4a630a2a9b4fbf807fa00e6dcafc9ce1a348&token=1627472701_b24a9df3556b20bcd805fce151204c22de119074
15:06:52 Tags saved for track "05. Hotel Pools - Splash feat. VIQ.mp3" from album "Palmscapes"
15:06:52 Downloaded track "05. Hotel Pools - Splash feat. VIQ.mp3" from album "Palmscapes"
15:06:52 Successfully downloaded album "Palmscapes"

```
</details>

**Comment by hstntt** [comment] 2021-07-27 17:55
@Otiel Is your downloader based on youtube-dl? Since audio files in youtube-dl are downloaded successfully, but the program also gives an error when trying to download cover art. 

`WARNING: Unable to download thumbnail "https://f4.bcbits.com/img/a4150604722_5.jpg": <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>`

Maybe I should also mention that I'm running Windows 7 x64 and .NET Framework 4.8.

**Comment by Otiel** [comment] 2021-07-27 18:03
@hstntt No, it has its own logic for downloading files. There has been reports from another user in Russia that the CDN delivering cover arts is blocked. Is it possible this is the case also in your country?

Are you using a proxy? In Windows settings, or in your browser settings?

**Comment by hstntt** [comment] 2021-07-27 18:19
@Otiel It seems that we have found the cause of the problem. I just ran everything through the system-wide proxy and everything worked perfectly. Downloaded cover art and everything else.

**Comment by Otiel** [comment] 2021-07-27 19:45
@hstntt Good, thanks for the feedback! That corroborates the fact that some ISP are blocking the cover arts CDN. 😕

@kokoropop Are you using a proxy as well? If not, can you try to set one in _Settings > Network_?

**Comment by LedAlex** [comment] 2021-08-03 22:42
Version 1.3.5.
I have the same issue. Already tried different network settings no, system and manual proxy.
Some time before it worked fine on same URL.

`2021-08-04 00:47:10.4729  ERROR  Failed to retrieve the size of the cover art file for album "Cyberpunk Epic Electro [No 
Copyright Music] / No More TearsCyberpunk Epic Electro by Infraction [No Copyright Music] / No More Tears". Hit max retries of 7. Progress update may be wrong.`
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/6927409/BandcampDownloader.log)

**Comment by dimeramid** [comment] 2021-08-07 06:26
Hi! I have been facing the same problem. I suppose the source of the trick is on the bandcamp side. Since a certain moment, there is something happening. When I access any bandcamp album page, from time to time I do not see images correctly. In the same time, your program fails exactly урут retreiving the image! 

![image](https://user-images.githubusercontent.com/88573133/128590668-e7a623ed-d0a4-46b6-b261-d4e4954b567b.png)

**Closed** 2022-02-20 17:19 UTC
Labels: help

**Comment by Otiel** [comment] 2022-02-20 17:27
There's a new option in [v1.4.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.4.0) that allows you to force downloading using HTTP instead of HTTPS. This should help those who see their HTTPS traffic to Bandcamp blocked.

Let me know if you find some issue with this new option.

**Comment by hstntt** [comment] 2022-03-02 16:10
I just tested the new feature and it solves the image problem. Thanks, greatly appreciated!
