### ISSUE TITLE
One-track downloading issue

### ISSUE THREAD

**Issue by sebw1nters** [Otiel/BandcampDownloader#38] opened 2017-06-30 23:44 UTC
When you download a single track, the year on the downloaded .mp3 file is saved as "1" instead of the correct release year.

**Comment by ajsnyde** [comment] 2017-07-02 21:48
Could not reproduce with the following url:
https://vegetables-belarus.bandcamp.com/track/feeling-sorry-for-us
Download yielded one mp3 with year as 2014.
Any chance you could give the url in question that is giving the problem?

**Comment by Otiel** [comment] 2017-07-03 09:05
I could not replicate this as well. As asked by @ajsnyde, can you share the URL you are using, as well as the string for the download folder (censor any username if needed)?

**Comment by Otiel** [comment] 2017-11-03 18:08
Closing this since we don't have enough information to reproduce. Please do comment if the error happens again.

**Closed by Otiel** 2017-11-03 18:08 UTC
Labels: bug, cannot-reproduce
