### ISSUE TITLE
App crashes when trying to open settings

### ISSUE THREAD

**Issue by AKmatiAK** [Otiel/BandcampDownloader#107] opened 2019-06-12 09:25 UTC
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/3280643/BandcampDownloader.log)

**Comment by Otiel** [comment] 2019-06-12 10:25
Can you please share your _ini_ file?

**Comment by AKmatiAK** [comment] 2019-06-12 16:05
[BandcampDownloader - Kopia.ini.txt](https://github.com/Otiel/BandcampDownloader/files/3282226/BandcampDownloader.-.Kopia.ini.txt)

**Comment by AKmatiAK** [comment] 2019-06-12 16:09
I don't know does this matter, but it also says cannot check for updates in bottom left corner.

**Comment by Otiel** [comment] 2019-06-12 16:43
Thanks for the _ini_ file, but I still can't reproduce this, this is weird.

* What OS do you have?
* What .NET Framework version is installed?

>it also says cannot check for updates in bottom left corner

That's not normal... Can you access the following page in your browser? https://github.com/Otiel/BandcampDownloader/releases/latest

**Comment by AKmatiAK** [comment] 2019-06-12 16:50
Win7
.NET 4.5.2

yes, I can access this page

**Comment by Otiel** [comment] 2019-06-12 16:59
BandcampDownloader is targeting .NET Framework 4.7.2. Do you have the possibility to upgrade your .NET Framework and see if that solves the problem(s)?

**Comment by AKmatiAK** [comment] 2019-06-12 17:32
updated .NET to 4.7.2 and works, but still shows cannot check for updates

**Comment by Otiel** [comment] 2019-06-12 18:15
What happens if you click "Check now" from the Settings window?

![image](https://user-images.githubusercontent.com/3851902/59375614-d0b50300-8d4e-11e9-84d7-0849d9e4c15f.png)

**Comment by Otiel** [comment] 2019-06-12 18:31
Let's continue in #109 for the update issue.

Closing this as the original issue has been solved by updating .NET Framework to 4.7.2.

**Closed by Otiel** 2019-06-12 18:31 UTC
Labels: cannot-reproduce
