### ISSUE TITLE
Error "Could not retrieve album info for <album_url>"

### ISSUE THREAD

**Issue by rpmsauron** [Otiel/BandcampDownloader#51] opened 2018-03-14 00:26 UTC
Since a while back, I can no longer download any album using this application, regardless of how my settings are or which album I try to download.
I just always get the error:

``
00:21:13 Starting download...
``
``
00:21:13 Retrieving album data for https://daedaleancomplex.bandcamp.com/album/eponym
``
``
00:21:14 Could not retrieve album info for https://daedaleancomplex.bandcamp.com/album/eponym
``

I am using v0.1.9.2.

**Comment by Otiel** [comment] 2018-03-14 08:36
I can't reproduce this bug. Can you check the "☑️ Verbose" log option and paste here the full content of the log?

I guess you tried to reset your settings to the default values?

**Comment by Blips150** [comment] 2018-03-14 15:07
I'm having similar issues, but in my case it says 

> 16:05:33 Could not retrieve data for http://polifauna.bandcamp.com/track/house-of-tin" itemprop="url"><span itemprop="name
and after trying to download the album itself, the program itself crashes.
Using v0.1.9.2. as well.

**Comment by Otiel** [comment] 2018-03-14 17:29
@Blips150 Thanks for your input. Unfortunately I cannot reproduce as well. It seems the page source isn't correctly downloaded.

What is the URL you're trying to download? Is it exactly (spaces & all) this:
```
http://polifauna.bandcamp.com/track/house-of-tin
```

**Comment by Blips150** [comment] 2018-03-14 18:23
@Otiel Well, the exact URL is https://polifauna.bandcamp.com and I ticked the following:

- Tag tracks

- Download artist discography

- Retrieve files size

- Save in tags

- Constrain maximum width/height (max size: 1000 px)

- Auto scroll

- Verbose

And after retrieving the file sizes for each song, the software just crashes before downloading anything, basically. Tried another artist's discography, but it's just the same.

**Comment by Blips150** [comment] 2018-03-14 21:42
@Otiel Btw there are times when it downloads the album, but it's 128 kbps, even though until now every single song I downloaded with it was 320.

**Comment by Blips150** [comment] 2018-03-14 21:55
Okay, something really weird happened. I tried ticking every box and I could download the entire album, but once again, it's in 128.. and it says it's done at 87,84 MB, but the album is seemingly a bit more.
![kepernyofelvetel 2663 _li](https://user-images.githubusercontent.com/37375535/37432967-7adb87e0-27da-11e8-959e-2a4d7b402d59.jpg)

**Comment by TadEro** [comment] 2018-03-14 22:32
the program can only download the files Bandcamp streams in the website; they are all max. 128kbps

**Comment by Otiel** [comment] 2018-03-15 15:40
@Blips150 Thanks, I was able to reproduce the bug with the URL https://polifauna.bandcamp.com. The issue comes from the fact that this artist has only one album. I still have to provide a fix for that. This bug is tracked in #21.
In the meantime, you can work around the issue by unchecking "☑️ Download artist discography" for artists that have only one album, or specify the album URL instead of the artist URL (in your case it's https://polifauna.bandcamp.com/album/you-look-like-a-lost-soul).

As said by @TadEro, Bandcamp streams are 128kbps. BandcampDownloader only downloads what you can listen to in your browser. I never heard about 320kbps streams on Bandcamp, I'm curious if you have a link as an example.

**Comment by Otiel** [comment] 2018-03-15 15:44
@rpmsauron I suppose that your issue is the same as @Blips150. Same answer: for artists that have only one album, either:
* Uncheck "☑ Download artist discography", or,
* Specify the album URL (https://[artist].bandcamp.com/[album]) instead of the artist URL.

This issue will be fixed when #21 is closed.

(If your problem is different, please comment and we'll re-open this issue)

**Closed by Otiel** 2018-03-15 15:44 UTC
Labels: cannot-reproduce
