### ISSUE TITLE
Downloads Lasting Forever

### ISSUE THREAD

**Issue by pogun1** [Otiel/BandcampDownloader#40] opened 2017-08-02 04:43 UTC
Sometimes when downloading an album, especially when there are large song names, the program will stop downloading, but when I check the files, everything is there, but the program will still be stuck in progress forever. This can be fixed by just restarting it, but in one particular case, it won't download this song no matter what.

https://carseatheadrest.bandcamp.com/track/this-one-time-i-went-to-a-coffee-house-because-some-guy-i-knew-was-playing-and-i-just-sat-there-for-an-hour-and-didnt-talk-to-anyone-and-then-i-came-home-and-wrote-this-song

**Comment by Otiel** [comment] 2017-08-02 11:53
I'll have a look at it.

Can you provide me some URL examples for the first issue you're reporting?

**Comment by pogun1** [comment] 2017-08-02 14:20
From what I remember, there is no pattern for the first problem, it just happens about half the time. I'll try to get some links of stuff I'm trying when I get home from work.

**Comment by Otiel** [comment] 2017-08-02 17:04
In that case, could you check the "☑ Verbose" option and paste the log here when this problem happens?

**Comment by pogun1** [comment] 2017-08-02 23:45
For the first issue, I tried to download an artist discography, which almost always fails in the way described. The download stopped, but when I check my files, every song is there, with tags. In issue two, I try to download the album with the one song that never works. The download never finished, and all songs were there except for the one.

[Bandcamp Errors.txt](https://github.com/Otiel/BandcampDownloader/files/1195565/Bandcamp.Errors.txt)

**Comment by 97Greyhound** [comment] 2017-11-15 15:24
Sometimes when downloading an album, especially when there are large song names, the program will stop downloading, but when I check the files, everything is there, but the program will still be stuck in progress forever. This can be fixed by just restarting it, but in one particular case, it won't download this song no matter what.
here is long
Unable to download track "02 EL ALTAR DEL HOLOCAUSTO - Cuando los sacerdotes que llevan el arca del Señor de toda la tierra metan los pies en el agua, el río se dividirá en dos partes, y el agua que viene de arriba dejará de correr y se detendrá como formando un embalse.mp3" from album "-H E-". Try 5 of 7

**Comment by Otiel** [comment] 2018-03-16 23:03
Fixed in release [0.1.9.3](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.9.3).

**Closed by Otiel** 2018-03-16 23:03 UTC
Labels: bug

**Comment by AKmatiAK** [comment] 2019-06-11 10:15
I got this issue in 2.10.0, it happens often when I download discography.

**Comment by Otiel** [comment] 2019-06-11 13:53
@AKmatiAK no crash, downloads lasting forever?

Does it happen randomly, or do you have a link where it happens systematically?

**Comment by AKmatiAK** [comment] 2019-06-11 14:34
https://ruinedconflict.bandcamp.com/
https://assemblage23.bandcamp.com/

happened at both
crashed only one time, I didn't focused on it

**Comment by Otiel** [comment] 2019-06-11 15:25
Thanks. I can't reproduce the bug for now, will keep looking.

Could you check the following and let me know if you have anything? 
`Event Viewer > Windows Logs > Application > Find > "BandcampDownloader"`

If not, an entry should be added next time you encounter the bug. I'm interested in "Error" entries and any stack trace that could be logged:

![image](https://user-images.githubusercontent.com/3851902/54033201-f234aa80-41b3-11e9-8fe6-348427a58556.png)

**Comment by Otiel** [comment] 2019-06-11 15:28
I've reproduced it, all good!

This is a different issue from #40. Please continue the discussion in #104.
