### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by potatoru** [Otiel/BandcampDownloader#98] opened 2019-06-02 07:52 UTC
Hello. App crashes randomly while download artist discography.

```2019-06-02 18:10:36.6835  DEBUG  Downloading track "where are you?" from url: https://t4.bcbits.com/stream/0b9bb3603d1eec4c718d8ad26e24717e/mp3-128/1726035003?p=0&ts=1559545144&t=d627f776b282d9097f16b234f8d6a8520ad9c28e&token=1559545144_c45a65271100776a3c919706869acb651016fcb9
2019-06-02 18:10:36.6975  DEBUG  Downloading track "sky full of stars" from url: https://t4.bcbits.com/stream/b3f11f75ca188473e7ad8b6e44d7a8b9/mp3-128/182891710?p=0&ts=1559545144&t=406367d3ae09ff09dd2937011c201fef8e8ca15e&token=1559545144_f2f0a3e0990db49e967615bc431a15e2c95a9f74
2019-06-02 18:10:36.6975  DEBUG  Downloading track "dreamin . . ." from url: https://t4.bcbits.com/stream/86ceb33d13dec5fa411045331563766e/mp3-128/4178555828?p=0&ts=1559545144&t=9004033946fbc258fdcb1cc3de11b188ff9566bb&token=1559545144_af05f5e6607db11ef4fa37d319cfff5b05f08e9e
2019-06-02 18:10:36.6975  DEBUG  Downloading track "mysterious" from url: https://t4.bcbits.com/stream/4d49be90fd258490eb579d9e08cfa4b1/mp3-128/367525853?p=0&ts=1559545144&t=6361d1c0bdc883f16246c244a5131a2640f2458c&token=1559545144_7ea6205bdca3ce945ff1efe877265f0614bacc6e
2019-06-02 18:10:36.6975  DEBUG  Downloading track "relax please" from url: https://t4.bcbits.com/stream/30bd11dc6f9173f42bff2782752e9c2c/mp3-128/2124074880?p=0&ts=1559545144&t=72943a656a4eb91315736bf1cac47a88ef383e8a&token=1559545144_3526b36f80f48d2946b0f873187b4128d1772789
2019-06-02 18:10:36.6975  DEBUG  Downloading track "natural beauty" from url: https://t4.bcbits.com/stream/d75de783ae098e0f41fd3ed33469d26d/mp3-128/3813281831?p=0&ts=1559545144&t=a01f6080241e4a85c3845c689b89f7e5152bc7e9&token=1559545144_9e1d052d7a2d9938061dec4ec4e52ab8e72e357f
2019-06-02 18:10:36.6975  DEBUG  Downloading track "stranger" from url: https://t4.bcbits.com/stream/32f2f8fc6a4b9f11ab1a368c5e58ec54/mp3-128/996853666?p=0&ts=1559545144&t=6ae1ed0536e48bb7b13f2f53ef6cff6947e5d0ac&token=1559545144_0084e62c69b0e8783301508efae8390fce901f49
2019-06-02 18:10:36.7125  DEBUG  Downloading track "under the rain" from url: https://t4.bcbits.com/stream/80bd42674bafbd7c05871db52a3623e1/mp3-128/2324693040?p=0&ts=1559545144&t=b7ff927fe0956515523793aeca26c42e3bd0a722&token=1559545144_a5e57ba77a9cd79081bf2ea53178965f6282b73e
2019-06-02 18:10:36.7125  DEBUG  Downloading track "bored" from url: https://t4.bcbits.com/stream/1912a3d5967f30015da6812486c156c8/mp3-128/2388400169?p=0&ts=1559545144&t=75c693c52cb200e8c3a11a8b787ccb21a72bbea9&token=1559545144_a2765fa6c59454038783d1141777b5f7cdd05226
2019-06-02 18:10:36.7125  DEBUG  Downloading track "beach" from url: https://t4.bcbits.com/stream/2c7b6d23977b798a24123efd6adf20ba/mp3-128/2961415121?p=0&ts=1559545144&t=d86415335277be396b61bf498c93910c94dd0961&token=1559545144_e54e4bca162cd8d7fc64dfaa624e80985981b998
2019-06-02 18:10:36.7125  DEBUG  Downloading track "hot summer" from url: https://t4.bcbits.com/stream/3c4f61063ab7ad94b248d745c3cd5180/mp3-128/668256562?p=0&ts=1559545144&t=5fd13bdede07c6c4cbcfba38dfbc27998346e768&token=1559545144_d5872832488c37830168c360796aa4b2e4fddb4b
2019-06-02 18:10:36.7125  DEBUG  Downloading track "chillin easy" from url: https://t4.bcbits.com/stream/99e32e946033da2309adddcc07f63d7c/mp3-128/3512184401?p=0&ts=1559545144&t=1f77209d372f549c63a0788d182577b1572aef86&token=1559545144_a3890c8b9b5171952eabf70e997a633531cda3c7
2019-06-02 18:10:36.7125  DEBUG  Downloading track "? club 1988" from url: https://t4.bcbits.com/stream/c2583e4e983fdfe9c6a6bce038d8e8bc/mp3-128/2710103875?p=0&ts=1559545144&t=94682f949d9061f23c226bf1161938a76895991d&token=1559545144_2542df6d695722f0830fac24568c7e92b0bf69d5
2019-06-02 18:10:36.7284  DEBUG  Downloading track "?? thoughts" from url: https://t4.bcbits.com/stream/d9e92a789b7f8a6d5421d50f1012c11e/mp3-128/2950978707?p=0&ts=1559545144&t=a68c5a6d8b6fb40230cf45fdbb84f2cd3c923c14&token=1559545144_4fd0867fdeae4f8d6622a2c1404ff4b3b51f0ec6
2019-06-02 18:10:36.7284  DEBUG  Downloading track "flashbacks" from url: https://t4.bcbits.com/stream/cce2f9daae2b420aac3a633015b37ade/mp3-128/824730437?p=0&ts=1559545144&t=ee073897c58246754e2533c2313fb7768bb1059e&token=1559545144_5413b704903559acf8f995b0d115d5fb6cec6766
2019-06-02 18:10:36.7284  WARN   Unable to download track "01 AVION - where are you?.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7284  WARN   Unable to download track "02 AVION - sky full of stars.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7284  WARN   Unable to download track "03 AVION - dreamin . . ..mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7444  WARN   Unable to download track "04 AVION - mysterious.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7444  WARN   Unable to download track "05 AVION - relax please.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7444  WARN   Unable to download track "06 AVION - natural beauty.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7444  WARN   Unable to download track "07 AVION - stranger.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7444  WARN   Unable to download track "08 AVION - under the rain.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7444  WARN   Unable to download track "09 AVION - bored.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7593  WARN   Unable to download track "10 AVION - beach.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7593  WARN   Unable to download track "11 AVION - hot summer.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7593  WARN   Unable to download track "12 AVION - chillin easy.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7593  WARN   Unable to download track "13 AVION - ? club 1988.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7593  WARN   Unable to download track "14 AVION - ?? thoughts.mp3" from album "d r e a m i n . . .". Try 1 of 7
2019-06-02 18:10:36.7593  WARN   Unable to download track "15 AVION - flashbacks.mp3" from album "d r e a m i n . . .". Try 1 of 7
```

```
DownloadsPath=D:\User\Desktop\plaza\bc\{artist}\{album}
AllowedFileSizeDifference=0.05
DownloadMaxTries=7
DownloadRetryCooldown=0.2
DownloadRetryExponent=4
SaveCoverArtInFolder=false
CoverArtFileNameFormat={album}
CoverArtInFolderConvertToJpg=true
CoverArtInFolderResize=false
CoverArtInFolderMaxSize=1000
SaveCoverArtInTags=true
CoverArtInTagsConvertToJpg=true
CoverArtInTagsResize=true
CoverArtInTagsMaxSize=1000
DownloadOneAlbumAtATime=true
RetrieveFilesSize=false
CheckForUpdates=false
EnableApplicationSounds=false
ShowVerboseLog=false
Language=en
Proxy=None
ProxyHttpAddress=
ProxyHttpPort=0
CreatePlaylist=false
M3uExtended=true
PlaylistFormat=m3u
PlaylistFileNameFormat={album}
FileNameFormat={tracknum} {artist} - {title}.mp3
ModifyTags=true
TagAlbumArtist=Modify
TagAlbumTitle=Modify
TagArtist=Modify
TagComments=Empty
TagLyrics=Modify
TagTrackNumber=Modify
TagTrackTitle=Modify
TagYear=Modify
DownloadArtistDiscography=true
```

**Comment by Otiel** [comment] 2019-06-02 18:02
Thanks for reporting this. For now I couldn't reproduce the crash, so it might be tricky to fix the bug. Does it always happen when there's multiple attempt to download a track ("Try 1 of 7"... in the log)?

**Comment by Otiel** [comment] 2019-06-03 07:10
Could you check the following and let me know if you have anything? 
`Event Viewer > Windows Logs > Application > Find > "BandcampDownloader"`

If not, an entry should be added next time you encounter the bug. I'm interested in "Error" entries and any stack trace that could be logged:

![image](https://user-images.githubusercontent.com/3851902/54033201-f234aa80-41b3-11e9-8fe6-348427a58556.png)

**Comment by potatoru** [comment] 2019-06-05 22:39
```
Application: BandcampDownloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess)
   at System.Net.WebClient.DownloadFileAsync(System.Uri, System.String, System.Object)

Exception Info: System.Net.WebException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.DownloadManager+<DownloadAndTagTrackAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.DownloadManager+<>c__DisplayClass13_0+<<DownloadAlbumAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.DownloadManager+<DownloadAlbumAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.DownloadManager+<StartDownloadsAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.WindowMain+<StartDownloadAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.WindowMain+<ButtonStart_Click>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at BandcampDownloader.App.Main()
```

**Comment by Otiel** [comment] 2019-06-12 09:13
Thanks. I'm not really sure what's causing this...

1. Is the album folder (`D:\User\Desktop\plaza\bc\AVION\Dreamin` in your example) correctly created even though the application crashes?
2. What OS and version are your running?
3. Can you let me know if it still happens with the new version ([1.0.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.0.0))?

**Comment by Otiel** [comment] 2019-08-07 13:12
Closing this as no new info has been provided.

**Closed by Otiel** 2019-08-07 13:12 UTC
Labels: bug, cannot-reproduce
